---
- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Upgrade all installed packages
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true
  environment:
    DEBIAN_FRONTEND: noninteractive
